<<<<<<< HEAD
# Generated by Django 3.2.17 on 2023-02-21 06:51
=======
# Generated by Django 3.2.17 on 2023-02-17 12:10
>>>>>>> 46c3ed6800e87b57e4a1e1c624342e115c30a982

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('core', '0004_auto_20230206_1628'),
=======
        ("core", "0004_auto_20230206_1628"),
>>>>>>> 46c3ed6800e87b57e4a1e1c624342e115c30a982
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.recipe_image_file_path),
=======
            model_name="recipe",
            name="image",
            field=models.ImageField(
                null=True, upload_to=core.models.recipe_image_file_path
            ),
>>>>>>> 46c3ed6800e87b57e4a1e1c624342e115c30a982
        ),
    ]
